### ISSUE TITLE
Comments to paper review

### ISSUE THREAD

**Issue by steo85it** [MillionConcepts/lhorizon#21]
I applied most of my suggestions directly to the text in PR #20  (I hope that's convenient for you, else let me know what you prefer). The structure and goals are clear and the article is generally well suited to present the software. However, here are some additional open remarks/questions:
- [x] **_Horizons_ is the only system in the world that provides...**: not really, other interfaces exist, such as https://ssp.imcce.fr/forms/ephemeris (and others under https://ssp.imcce.fr/forms ) or http://iaaras.ru/en/dept/ephemeris/online/ . The statement could be "weakened" (here and else in the text, e.g., "_Horizons_ is one of the main providers of" or "among few providers of ... in the world.") to make it a bit fairer to other groups.
- [x] **"_Horizons_ is high-precision"**: what does "high precision" mean?
- [x] **"has the capability to produce corrected positions"**: what does "corrected" mean here? "corrected" of what effects/errors/etc?
- [x] **"had experienced bitrot"** : this is slang and at least it's not familiar to me
- [x] **"JPL is the most authoritative producer of solar system ephemerides"**: again, this is arbitrary and should be weakened to "one of the few", "one of the most", etc... Several institutes in the world provide ephemerides of comparable accuracy and relevance, notably JPL produces DE, IMCCE produces INPOP (the french/european ephemeris), and the RAS produces EPM (Russian ephemeris). At least the first 2 are regularly used in the framework of space missions.
- [x] **"“simple” quantities like the solar angle"**: which angle? azimuth? elevation? maybe "solar angleS" would easily solve this.
- [x] **"also collecting the appropriate data files, called “kernels.”**: I know by experience that this is often tricky, but wouldn't your examples also get into the same trouble when calling spiceypy (e.g., for reference frames transformations)? If you found a way to automatically load dependencies for the high-level kernels, this should definitely be highlighted more (it would be awesome!!).
- [x] **"automatically-generated kernels"**: what do you mean here?
- [x] **"up to tens of millions of kernels"**: did you really count them? All version summed together? :) Anyway, the sentence was extremely redundant.
- [x] as a general remark, I think the paragraph about SPICE was way too harsh and colloquial. Also, it's hard to defend subjective statement such as "extremely high barrier" or "is difficult for planetary scientists and specialized engineers" (it's not, after you get accustomed to it, as for most software packages). I get your point (mostly), but the language needed amendments (mine in this PR is just a suggestion).
- [x] **"it cover more sites"**: what does this mean? which "sites"?
- [x] **"geometry data"**: it would be good to define this somewhere (rather early in the text), as it's somehow the focus and might be unclear to general readers/users. Also, I'm not sure whether "geometry data" or "geometric data" or "geometry" (e.g., of an observation) would be the correct terminology.
- [x] **Other Related Work**: references to the (very much active) CALCEPH library (https://www.imcce.fr/inpop/calceph/ for C, fortran, python, Matlab interfaces) is missing.
- [x] **Statement of Need**: as a potential user reading this, I would find it useful to have some examples of applications (such as a brief summary of the jupiter notebooks you prepared). This would be a good place to briefly present and reference them.
- [x] well, include suggestions (or similar changes) as included in PR #20 
- [x] consistently update README.md

openjournals/joss-reviews#3495

**Comment by m-stclair** [comment]
> I applied most of my suggestions directly to the text in PR #20 (I hope that's convenient for you, else let me know what you prefer). 

Thank you for your notes! I've been chasing a deadline for the past week and am just getting back to this now; sorry about the delay. I accepted your PR,  added some rewrites and additional edits in response to your comments, and ticked off the items in your comment I think are probably fully resolved. Further discussion below:

>  **_Horizons_ is the only system in the world that provides...**: not really, other interfaces exist...

You are right; this claim is excessively parochial. I have weakened such statements throughout.

>  **"_Horizons_ is high-precision"**: what does "high precision" mean?

I meant it as a qualitative description, but I have specified it in context. It can be entirely removed if you think it's misleading or irrelevant.

> 
>  **"has the capability to produce corrected positions"**: what does "corrected" mean here? "corrected" of what effects/errors/etc?

Clarified this in the text.

>  **"had experienced bitrot"** : this is slang and at least it's not familiar to me

I replaced this term with a full description of the phenomenon.

> 
> **"also collecting the appropriate data files, called “kernels.”**: I know by experience that this is often tricky, but wouldn't your examples also get into the same trouble when calling spiceypy...

Most of `lhorizon` does not use SPICE at all, wrapped in `spiceypy` or otherwise. One piece of functionality in an optional portion of the module uses SPICE to do the last step (a reference frame transformation) of an operation that, end-to-end, it is difficult to perform using only either Horizons or SPICE. The value proposition of this piece of functionality should be considered primarily capability rather than usability, although this is not true for most of `lhorizon`. Do you think I need to add an explicit discussion of this somewhere?

> **"automatically-generated kernels"**: what do you mean here?

I meant: there are a number of services that procedurally generate SPICE kernels. _Horizons_, for instance (though only at its telnet endpoint), given various parameters, will custom-produce SPK kernels for small bodies valid in particular time windows, etc. This is really tangential to the paper, though, and I have just removed it.

>  **"up to tens of millions of kernels"**: did you really count them? All version summed together? :) Anyway, the sentence was extremely redundant.

Haha no. Just a rough order-of-magnitude estimate. Anyway, as you say, there is not really any need for this part of the discussion, and I have removed it.

>  as a general remark, I think the paragraph about SPICE was way too harsh and colloquial. Also, it's hard to defend subjective statement such as "extremely high barrier" or "is difficult for planetary scientists and specialized engineers" (it's not, after you get accustomed to it, as for most software packages)...

It is certainly true that assessments of usability have subjective elements, and that training effects are major confounders for these assessments. I think the thrust of your amendments makes sense.

> **"it cover more sites"**: what does this mean? which "sites"?

Clarified this in the text.

>  **"geometry data"**: it would be good to define this somewhere (rather early in the text), as it's somehow the focus and might be unclear to general readers/users. Also, I'm not sure whether "geometry data" or "geometric data" or "geometry" (e.g., of an observation) would be the correct terminology.

Yes, this is an ugly term. I don't know what is best. "Geometry data" is common jargon in NAIF publications, but it might not be used as widely as I think it is. I agree that "geometric" sounds more grammatical, but it is somewhat overloaded in this context, as it is sometimes used to refer to "true" position (as opposed to "astrometric" position with target-observer light-time, and sometimes other corrections, applied). Do you think there is another term that would be clearer to a general audience?

> **Other Related Work**: references to the (very much active) CALCEPH library (https://www.imcce.fr/inpop/calceph/ for C, fortran, python, Matlab interfaces) is missing.

Yes, that's an oversight. I've added this to the text. Do you know if CALCEPH has a preferred citation? I can't find an explicit statement about it.

**Comment by m-stclair** [comment]
brief discussion of use cases in paper and tweaks to readme: 6b5a947

**Comment by steo85it** [comment]
Thanks for your changes and comments, the paper looks clearer now in my opinion. I just suggested a few minor modifications in PR #25 , along with suggesting to use the CALCEPH website as reference for it. The rest is good for me now.

**Comment by m-stclair** [comment]
Great. I have accepted your PR and added a reference to the CALCEPH website: c70f82d. Thanks again!
