### ISSUE TITLE
examples/target_example.ipynb

### ISSUE THREAD

**Issue by steo85it** [MillionConcepts/lhorizon#23]
This is an interesting example of application of your package and functions!
However, am I right to say that "In 8" and the whole Part 2 fully rely on SPICE/spicey-py?  You correctly state at some point that "additional kernels might be needed for different applications", but still it is not clearly stated that in order to get those functionalities (reference frame changes) one needs to load, use and understand spice kernels (which is fine, but also an issue that you extensively claim to avoid in your paper).

openjournals/joss-reviews#3495

**Comment by steo85it** [comment]
Also, minor point: what do you mean by `earth mean equator and equinox of J2000, **often called "J2000" for historical reasons**`? It's simply called J2000 because it refers to the equator at 01/01/2000 12:00:00.

**Comment by m-stclair** [comment]
> This is an interesting example of application of your package and functions!
> However, am I right to say that "In 8" and the whole Part 2 fully rely on SPICE/spicey-py? 

Yes, this specific piece of `lhorizon.target`'s functionality relies on SPICE via spiceypy; unlike most of `lhorizon`, its added value should probably be considered in terms of functionality rather than usability (although if you are only interested in the SPICE built-in frames + the high-precision Moon frames, the included kernels offer a completely abstracted interface). Do you think I need to add a longer discussion of this somewhere? See also my response to your related comment in your thread on the paper.

**Comment by m-stclair** [comment]
> Also, minor point: what do you mean by `earth mean equator and equinox of J2000, **often called "J2000" for historical reasons**`? It's simply called J2000 because it refers to the equator at 01/01/2000 12:00:00.

I mean that "J2000" is an ambiguous name for a reference frame. It refers to the time, but there are other reference frames that use J2000 as an epoch but are not the "J2000" frame. I have encountered metadata that referred to quite different frames (like the ecliptic system SPICE calls "ECLIPJ2000") as "J2000"  because they used the J2000 epoch. More narrowly, in this case, I am gesturing to the fact that SPICE now uses the ICRF reference frame rather than the FK5 J2000 frame but retains the "J2000" identifier for it. Because they are so close, it is unlikely to cause numerical problems for the vast majority of use cases, but is still a potential source of confusion -- particularly because _Horizons_ does _not_ retain the "J2000" identifier for this reference frame. For these reasons, I like to give a general warning about this term. If you think it is confusing or unnecessary here, though, I can certainly cut it.

**Comment by steo85it** [comment]
> Yes, this specific piece of `lhorizon.target`'s functionality relies on SPICE via spiceypy; unlike most of `lhorizon`, its added value should probably be considered in terms of functionality rather than usability (although if you are only interested in the SPICE built-in frames + the high-precision Moon frames, the included kernels offer a completely abstracted interface). Do you think I need to add a longer discussion of this somewhere? See also my response to your related comment in your thread on the paper.

I would probably add a comment about this in the notebook (or section) docstring, just mentioning that `for this step, SPICE kernels have been loaded from the XX folder. For applications to different bodies or frames you might need to load different/additional kernels - or different versions thereof.` (or something along these lines).

> I mean that "J2000" is an ambiguous name for a reference frame. It refers to the time, but there are other reference frames that use J2000 as an epoch but are not the "J2000" frame. ...

I would remove the `for historical reasons`, then the sentence would be fine for me.

**Comment by m-stclair** [comment]
> I would probably add a comment about this in the notebook (or section) docstring, just mentioning that `for this step, SPICE kernels have been loaded from the XX folder. For applications to different bodies or frames you might need to load different/additional kernels - or different versions thereof.` (or something along these lines).

I have a comment about that in the section, and added one to the cell containining the call to `load_metakernel()` to make it clearer what that function is doing.  

> I would remove the `for historical reasons`, then the sentence would be fine for me.

Got it. I removed that and replaced it with 'earth mean equator and equinox of 01/01/2000 12:00, called "ICRF" by Horizons and "J2000" by SPICE', which is what I really wanted to draw attention to.

These changes are applied in 1fc5646.
